/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dental_clinic_sys;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asmaa
 */


public class Examination extends javax.swing.JFrame {
    String first  , last , phonenum , history  , statue  ;
    double price ; 
    
    
 //DefaultTableModel dtm ; 
    
    
    
    Connection con;
    //ArrayList<Integer> deptsIds = new ArrayList<>();
    
    /**
     * Creates new form Examination
     */
    public Examination() {
        initComponents();
        this.setLocationRelativeTo(null);
        
      
        try {
             con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", "root", "root");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Connection failed");
        }
        
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        finame = new javax.swing.JTextField();
        laname = new javax.swing.JTextField();
        statuecombobox = new javax.swing.JComboBox<>();
        date = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Labelcost = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Examination ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        finame.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(finame, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 218, 30));

        laname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        laname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanameActionPerformed(evt);
            }
        });
        jPanel2.add(laname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 210, 30));

        statuecombobox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        statuecombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cavities", "Gingivitis/Periodontitis", "Tooth Sensitivity", "Tooth Abscess", "Bad Breath", "Malocclusion", " " }));
        jPanel2.add(statuecombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 170, -1));

        date.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 290, 30));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 139, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Public\\Pictures\\R.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 280, 100, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Public\\Pictures\\25845a2b3ec629b43eef4ed89c8a.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 290, 210));

        Labelcost.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Labelcost.setText("Cost:");
        Labelcost.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(Labelcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 110, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("FirstName:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("SecondName:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 120, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Date:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 80, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (!finame.getText().isEmpty() &&  ! laname.getText().isEmpty() &&  ! date.getText().isEmpty() ){
            
            try {
                first = finame.getText();
                last = laname.getText() ;
                history = date.getText();
                statue = statuecombobox.getSelectedItem().toString() ;
                switch (statue){
                    case "Cavities":
                        Labelcost.setText("700");
                        price = 700 ; 
                        break;
                        
                    case "Gingivitis/Periodontitis":
                        Labelcost.setText("800");
                        price = 800 ; 
                        break;
                        
                        
                    case "Tooth Sensitivity":
                        Labelcost.setText("500");
                        price = 500 ; 
                        break;
                        
                        
                    case "Tooth Abscess":
                        Labelcost.setText("900");
                        price = 900 ; 
                        break;
                        
                        
                    case "Bad Breath":
                        Labelcost.setText("400");
                        price = 400 ;
                        break;
                        
                        
                    case "Malocclusion":
                        Labelcost.setText("1500");
                        price = 1900 ; 
                        
                        break;
                        
                        
                    default:
                        Labelcost.setText("");
                        break;
                        
                }
                
                //JOptionPane.showMessageDialog(this, first +fir " " + last + " " + history + " " + statue );
                 String sql = "select * from customers where First_name='" + first +"' AND Last_name='" + last +"'AND phone="' ";
                PreparedStatement stmt = con.prepareStatement("insert into records(First_name,last_name,phone,age,gender,address ,date, statue , cost ) values(?,?,?,?,? ,?,?,?,?)");
                   stmt.setString(1, first); 
                   stmt.setString(2, last); 
                   stmt.setString(3, " "); 
                   stmt.setDouble(4, 18 ); 
                   stmt.setString(5, " ");
                   stmt.setString(6, " ");
                   stmt.setString(7, " ");
                   stmt.setString(8,statue); 
                   stmt.setDouble(9, price); 
                   
                    
                stmt.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Added Succsesfully");
                
                
                
            } catch (SQLException ex) {
                Logger.getLogger(Examination.class.getName()).log(Level.SEVERE, null, ex);
            }
  
        }
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    
    
    
    
    
    
    
    private void lanameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lanameActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    /**
     * @param args the command line arguments
     */
    

    
    
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Examination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Examination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Examination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Examination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Examination().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Labelcost;
    private javax.swing.JButton btnAdd;
    private javax.swing.JTextField date;
    private javax.swing.JTextField finame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField laname;
    private javax.swing.JComboBox<String> statuecombobox;
    // End of variables declaration//GEN-END:variables
}
