/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dental_clinic_sys;

import java.awt.Color;

/**
 *
 * @author Administrator
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
   // Login log = new Login();
    public HomePage() {
        Login log = new Login();
        initComponents();
        this.setLocationRelativeTo(null);
        
        if(log.username.equals("admin"))
            btnSettings.setEnabled(true);
        else
        btnSettings.setEnabled(false);

            
        

            
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnRes = new javax.swing.JButton();
        btnFinances = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnSettings = new javax.swing.JButton();
        btnBooking = new javax.swing.JButton();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("dental clinic management system");
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 563));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 520, -1, -1));

        btnRes.setBackground(new java.awt.Color(255, 255, 255));
        btnRes.setText("Resources");
        btnRes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnResMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResMouseExited(evt);
            }
        });
        btnRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResActionPerformed(evt);
            }
        });
        jPanel1.add(btnRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 180, 30));

        btnFinances.setBackground(new java.awt.Color(255, 255, 255));
        btnFinances.setText("Finances");
        btnFinances.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFinancesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFinancesMouseExited(evt);
            }
        });
        btnFinances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinancesActionPerformed(evt);
            }
        });
        jPanel1.add(btnFinances, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 180, 30));

        btnNew.setBackground(new java.awt.Color(255, 255, 255));
        btnNew.setText("Add customer");
        btnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseentered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomePage.this.mouseExited(evt);
            }
        });
        jPanel1.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 180, 30));

        btnView.setBackground(new java.awt.Color(255, 255, 255));
        btnView.setText("View appointments");
        btnView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewMouseExited(evt);
            }
        });
        jPanel1.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 180, 30));

        btnSettings.setText("Settings");
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });
        jPanel1.add(btnSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 80, -1));

        btnBooking.setBackground(new java.awt.Color(255, 255, 255));
        btnBooking.setText("Booking");
        btnBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBookingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBookingMouseExited(evt);
            }
        });
        btnBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookingActionPerformed(evt);
            }
        });
        jPanel1.add(btnBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 180, 30));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/homeScreen.png"))); // NOI18N
        jPanel1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinancesActionPerformed
        // TODO add your handling code here:
        Finances fin = new Finances();
        fin.show();
    }//GEN-LAST:event_btnFinancesActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
        Login login = new Login();
        login.show();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        // TODO add your handling code here:
        settings stg = new settings();
        stg.show();
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void btnBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBookingActionPerformed

    private void mouseentered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseentered
        btnNew.setBackground(new Color(57, 71, 147));

    }//GEN-LAST:event_mouseentered

    private void mouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExited
        // TODO add your handling code here:
        btnNew.setBackground(new Color(255, 255, 255));

    }//GEN-LAST:event_mouseExited

    private void btnResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResActionPerformed
        // TODO add your handling code here:
        Resources res = new Resources();
        res.show();
    }//GEN-LAST:event_btnResActionPerformed

    private void btnBookingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingMouseEntered
        // TODO add your handling code here:
        btnBooking.setBackground(new Color(57, 71, 147));

    }//GEN-LAST:event_btnBookingMouseEntered

    private void btnBookingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBookingMouseExited
        // TODO add your handling code here:
        btnBooking.setBackground(new Color(255, 255, 255));

    }//GEN-LAST:event_btnBookingMouseExited

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setBackground(new Color(255, 0, 0));

    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setBackground(new Color(255, 255, 255));

    }//GEN-LAST:event_btnExitMouseExited

    private void btnResMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResMouseEntered
        // TODO add your handling code here:
        btnRes.setBackground(new Color(57, 71, 147));

    }//GEN-LAST:event_btnResMouseEntered

    private void btnResMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResMouseExited
        // TODO add your handling code here:
        btnRes.setBackground(new Color(255, 255, 255));

    }//GEN-LAST:event_btnResMouseExited

    private void btnViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMouseEntered
        // TODO add your handling code here:
        btnView.setBackground(new Color(57, 71, 147));

    }//GEN-LAST:event_btnViewMouseEntered

    private void btnViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMouseExited
        // TODO add your handling code here:
        btnView.setBackground(new Color(255, 255, 255));

    }//GEN-LAST:event_btnViewMouseExited

    private void btnFinancesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinancesMouseEntered
        // TODO add your handling code here:
        btnFinances.setBackground(new Color(57, 71, 147));

    }//GEN-LAST:event_btnFinancesMouseEntered

    private void btnFinancesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinancesMouseExited
        // TODO add your handling code here:
        btnFinances.setBackground(new Color(255, 255, 255));

    }//GEN-LAST:event_btnFinancesMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBooking;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFinances;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRes;
    private javax.swing.JButton btnSettings;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel img;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
