/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dental_clinic_sys;

import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author Administrator
 */
public class SplashScreen extends  javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }
    private void bar(){

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bar = new javax.swing.JProgressBar();
        loadingValue = new javax.swing.JLabel();
        loadingLabel = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 338));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 250));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar.setBackground(new java.awt.Color(255, 255, 255));
        bar.setBorderPainted(false);
        jPanel1.add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 600, 17));

        loadingValue.setForeground(new java.awt.Color(153, 0, 153));
        loadingValue.setText("0%");
        jPanel1.add(loadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, -1, -1));

        loadingLabel.setForeground(new java.awt.Color(153, 0, 153));
        loadingLabel.setText("Loading...");
        jPanel1.add(loadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/splashScreen.png"))); // NOI18N
        image.setText("jLabel2");
        jPanel1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 600, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        SplashScreen sp = new SplashScreen();
        sp.setVisible(true);
//        sp.bar.setStringPainted(true);
//        sp.bar.setBackground(Color.red);
//        sp.bar.setForeground(Color.blue);

        try{
        for(int i = 0 ;i<=100;i++){
        Thread.sleep(50);
        sp.loadingValue.setText(i + "%");
        sp.bar.setValue(i);
        if(i ==10){
            sp.loadingLabel.setText("Turning On Moudules...");              

        }
       if(i ==20){
            sp.loadingLabel.setText("Loading Moudule...");              

       }
       if(i ==50){
            sp.loadingLabel.setText("connecting to Database...");              

       }
        if(i ==70){
            sp.loadingLabel.setText("connection Successful !...");              
            }
        if(i ==80){
            sp.loadingLabel.setText("Lanuching Application...");              
            }
        if(i ==100){

            }

        }
        
        sp.dispose();
        new Login().setVisible(true);
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }

        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bar;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loadingLabel;
    private javax.swing.JLabel loadingValue;
    // End of variables declaration//GEN-END:variables
}
